import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { circleIntersectsBox, moveWithCollisions } from '../src/collision.js';
import { VIEWS, ANCHORS, BENCHES, TABLES } from '../src/layout.js';
const wall={minX:1,maxX:1.1,minZ:-10,maxZ:10};
test('walk cannot tunnel through a thin wall, even on a very large step',()=>{const p=moveWithCollisions({x:0,z:0},10,0,[wall]);assert.ok(p.x<=.781);assert.ok(p.x>.65);});
test('diagonal movement slides along a wall instead of crossing it',()=>{const p=moveWithCollisions({x:.75,z:0},2,3,[wall]);assert.ok(p.x<=.781);assert.ok(p.z>2.99);});
test('circle collision allows corners without treating the avatar as a square',()=>{const b={minX:0,maxX:1,minZ:0,maxZ:1};assert.equal(circleIntersectsBox(-.2,-.2,b),false);assert.equal(circleIntersectsBox(-.1,-.1,b),true);});
test('every viewpoint starts outside furniture and walls',async()=>{const {colliders}=JSON.parse(await readFile('public/assets/classroom-layout.json'));for(const [name,view] of Object.entries(VIEWS)){const overlaps=colliders.filter(b=>circleIntersectsBox(view.position[0],view.position[2],b));assert.deepEqual(overlaps.map(x=>x.name),[],name+' must be clear');}});
test('activity anchors sit on their intended table surfaces',()=>{const lever=ANCHORS.find(a=>a.name==='GameAnchor_Lever').position,design=ANCHORS.find(a=>a.name==='GameAnchor_Design').position;assert.equal(lever[0],BENCHES[2].x);assert.equal(lever[2],BENCHES[2].z);assert.ok(Math.abs(lever[1]-(BENCHES[2].height+.085/2))<.002);assert.equal(design[0],TABLES[1].x);assert.ok(Math.abs(design[1]-(TABLES[1].height+.065/2))<.002);});
